name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn run eslint . --fix --ext .js,.jsx,.ts,.tsx,.md,.json
    - name: Run prettier
      run: yarn run prettier --write "./src/**/*.{ts,tsx,js,md}"